"""
Shim de compatibilité — re-exporte tout depuis les trois modules spécialisés.
Importer directement depuis matching, audit ou markdown est préférable pour
le nouveau code, mais tous les importeurs existants continuent de fonctionner.
"""
# Re-exports intentionnels — les hints "not accessed" sont attendus dans un shim.
from .matching import (  # noqa: F401
    find_candidate_evidence_for_requirement,
    build_requirement_groups,
    GENERIC_STOPWORDS,
    INVALID_REQUIREMENT_PHRASES,
    LOCATION_NOISE_TERMS,
    GENERIC_REQUIREMENT_HINTS,
    TITLE_UNSAFE_IF_NOT_CONFIRMED,
    SAFE_TITLE_QUALIFIERS,
    SAFE_CONTEXT_TERMS,
    compute_matching_score,
    compute_matching_score_details,
    _contains_phrase,
    _display_text,
    _title_piece,
    _clean_requirement,
    _clean_offer_title,
    extract_offer_title,
    _unsafe_title_terms,
    _safe_title_segment,
    build_dynamic_title,
    extract_safe_context_terms,
    extract_offer_sector,
    enrich_matching_with_offer_context,
    _requirement_key,
    _add_requirement,
    compact_requirements,
    extract_requirements_from_offer,
    is_transferable_requirement,
    split_requirement_parts,
    is_valid_requirement,
    infer_recommended_title,
    classify_requirement,
    build_fallback_matching,
    enrich_matching_with_extracted_requirements,
    normalize_matching_requirements,
    adjust_for_training_context,
    apply_cross_requirement_reasoning,
    enrich_matching_with_implicit_requirements,
    candidate_total_years,
    candidate_max_education,
    complete_matching_safety_fields,
    allowed_evidence_from_matching,
)

from .audit import (  # noqa: F401
    contains_forbidden_claim,
    contains_unsupported_claim,
    validate_generated_cv,
    build_safe_summary,
    resolve_safe_title,
    resolve_safe_summary,
    resolve_safe_email,
)

from .markdown import (  # noqa: F401
    MONTHS_FR,
    _year_only,
    _month_year,
    _format_cv_date,
    _format_location,
    _is_database_cv,
    _format_achievement,
    extract_static_cv_sections,
    group_experience_bullets,
    build_skill_experience_map,
    annotate_audit_skills,
    stack_for_source,
    generate_database_recruiter_markdown,
    generate_recruiter_markdown,
    generate_email_markdown,
    generate_audit_markdown,
    generate_markdown,
    save_outputs,
)
